apiVersion: v1
kind: Service
metadata:
  labels:
    app: canary-app
  name: canary-svc
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 50001
      targetPort: 8080
  selector:
    app: canary-app
  externalIPs:
    - 192.168.219.100


