apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-svc
  namespace: default
spec:
  ports:
  - port: 50001
    protocol: TCP
    targetPort: 8080
  selector:
    app: myapp
  type: NodePort
