apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-resnet18
  labels:
    app: myapp
    version: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: stable
  template:
    metadata:
      labels:
        app: myapp
        version: stable
    spec:
      containers:
      - name: testapp
        image: with1015/flask-resnet18
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
