apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-resnet18
  labels:
    app: canary-app
    version: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-app
      version: stable
  template:
    metadata:
      labels:
        app: canary-app
        version: stable
    spec:
      containers:
      - name: flask-resnet18-gpu
        image: with1015/flask-resnet18
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
