apiVersion: apps/v1
kind: Deployment
metadata:
  name: kserve-resnet18-cpu
  labels:
    app: canary-app
    version: canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: canary-app
      version: canary
  template:
    metadata:
      labels:
        app: canary-app
        version: canary
    spec:
      containers:
      - name: kserve-resnet18-cpu
        image: with1015/kserve-resnet18-cpu
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
